import { createContext, useContext, useState } from 'react';

const translations = {
  en: {
    nav: {
      smartphones: 'Smartphones',
      laptops: 'Laptops',
      accessories: 'Accessories',
      repairs: 'Repairs',
      about: 'About Us',
      contact: 'Contact',
      shop: 'Shop',
      signIn: 'Sign In',
      dashboard: 'Dashboard',
      logout: 'Logout',
    },
    home: {
      heroBadge: 'Est. 2015',
      heroTitle1: 'Quality',
      heroTitle2: 'Refurbished',
      heroTitle3: 'Electronics',
      heroDesc: 'Every device is inspected, tested, and certified by our expert technicians. Backed by a 1-year warranty and free shipping.',
      browseStore: 'Browse Store',
      bookRepair: 'Book a Repair',
      stat1: 'Point Inspection',
      stat2: 'Happy Customers',
      stat3: 'Warranty',
      featured: 'Featured',
      bestSellers: 'Our Best Sellers',
      bestSellersDesc: 'Top-rated certified pre-owned devices.',
      whyChoose: 'Why Choose Us',
      whyTitle: 'Setting the Standard for',
      whyTitleAccent: 'Refurbished Tech',
      whyDesc1: 'Since 2015, Shree Renukamba Communication has been dedicated to providing premium refurbished electronics and expert mobile repair services. We believe that top-tier technology shouldn\'t cost the earth.',
      whyDesc2: 'Every device we sell undergoes a rigorous 45-point inspection process by our certified technicians, ensuring that you receive a product that looks and performs like new.',
      val1: '45-Point Inspection',
      val2: '30-Day Returns',
      val3: 'Free Delivery',
      val4: '1-Year Warranty',
      categories: 'Categories',
      shopByCategory: 'Shop by Category',
      shopByCategoryDesc: 'Browse our curated selection of devices',
      reviews: 'Reviews',
      whatCustomersSay: 'What Our Customers Say',
      stayUpdated: 'Stay Updated',
      stayUpdatedDesc: 'Get exclusive deals, new arrivals, and repair tips by email.',
      subscribe: 'Subscribe',
      emailPlaceholder: 'Enter your email address',
      newStocks: 'New Arrivals',
      newStocksDesc: 'Freshly added devices with the latest models and best deals.',
      justAdded: 'Just Added',
      viewAll: 'View All Products',
    },
    shop: {
      filters: 'Filters',
      search: 'Search',
      categories: 'Categories',
      all: 'All',
      condition: 'Condition',
      priceRange: 'Price Range',
      clearAll: 'Clear All Filters',
      sort: 'Sort by',
      recommended: 'Recommended',
      addToCart: 'Add',
      outOfStock: 'Out of Stock',
      inStock: 'In Stock',
      only: 'Only',
      left: 'left',
      viewDetails: 'View Details',
      noProducts: 'No products found',
      noProductsDesc: 'Try adjusting your filters.',
      available: 'available',
    },
    product: {
      backTo: 'Back to',
      category: 'Category',
      sku: 'SKU',
      reviews: 'reviews',
      save: 'Save',
      description: 'Description',
      specifications: 'Specifications',
      fullSpecs: 'Full Specifications',
      quantity: 'Quantity',
      addedToCart: 'Added to Cart',
      addToCart: 'Add to Cart',
      relatedProducts: 'Related Products',
      certifiedQuality: 'Certified Quality',
      certifiedDesc: '45-point inspection',
      freeShipping: 'Free Shipping',
      shippingDesc: 'On all orders',
      easyReturns: '30-Day Returns',
      returnsDesc: 'No questions asked',
      productDetails: 'Product Details',
    },
    footer: {
      brandDesc: 'Your trusted source for certified refurbished electronics and professional repair services since 2015.',
      shop: 'Shop',
      support: 'Support',
      aboutUs: 'About Us',
      bookRepair: 'Book a Repair',
      shipping: 'Shipping & Delivery',
      returns: 'Returns & Exchanges',
      faqs: 'FAQs',
      contactUs: 'Contact Us',
      allProducts: 'All Products',
      tablets: 'Tablets',
      rights: 'All Rights Reserved.',
      privacy: 'Privacy Policy',
      terms: 'Terms of Service',
      cookies: 'Cookie Policy',
    },
    about: {
      heroTitle: 'About Us',
      heroDesc: 'Shree Renukamba Communication has been the trusted name for premium refurbished electronics and professional repair services since 2015.',
      ourStory: 'Our Story',
      storyTitle: 'Quality Technology for Everyone',
      storyP1: 'Founded in Bengaluru, Shree Renukamba Communication started with a simple mission: make premium technology accessible to everyone. We saw a market flooded with overpriced new devices and low-quality used ones - and knew there had to be a better way.',
      storyP2: 'By building relationships with certified suppliers and developing rigorous testing protocols, we created a curated marketplace where every device is inspected, certified, and backed by a warranty you can trust.',
      storyP3: 'Today, we serve thousands of happy customers across India, offering everything from smartphones and laptops to tablets and accessories - all at prices that make sense.',
      happyCustomers: 'Happy Customers',
      devicesSold: 'Devices Sold',
      avgRating: 'Avg. Rating',
      yearsExp: 'Years Experience',
      whatWeDo: 'What We Do',
      whatWeDoDesc: 'Two core services that set us apart',
      ecomTitle: 'E-Commerce Store',
      ecomDesc: 'We curate and sell certified refurbished electronics - smartphones, laptops, tablets, smartwatches, and accessories. Each device passes a rigorous 45-point inspection and comes with a full warranty.',
      repairTitle: 'Repair Services',
      repairDesc: 'From screen replacements to battery upgrades and water damage repair, our certified technicians handle all major brands and models. Fast turnaround with genuine parts.',
      browseStore: 'Browse Store',
      bookRepair: 'Book a Repair',
      whyChoose: 'Why Choose Us',
      whyChooseDesc: 'We stand behind every device and every repair',
      meetTeam: 'Meet Our Team',
      meetTeamDesc: 'Passionate people behind the brand',
      readyToStart: 'Ready to Get Started?',
      readyDesc: 'Browse our collection of certified devices or book a repair appointment today.',
      shopNow: 'Shop Now',
    },
    contact: {
      heroTitle: 'Contact Us',
      heroDesc: 'Have a question? We\'d love to hear from you. Send us a message and we\'ll respond as soon as possible.',
      getInTouch: 'Get In Touch',
      letsTalk: 'Let\'s Talk',
      visitUs: 'Visit Us',
      callUs: 'Call Us',
      emailUs: 'Email Us',
      businessHours: 'Business Hours',
      hours: 'Mon - Sat: 10:00 AM - 8:00 PM',
      sunHours: 'Sunday: 11:00 AM - 5:00 PM',
      quickResponse: 'Quick Response',
      quickDesc: 'We typically respond within 2-4 hours during business hours. For urgent repairs, please call us directly.',
      sendMessage: 'Send a Message',
      fullName: 'Full Name',
      email: 'Email',
      subject: 'Subject',
      message: 'Message',
      yourName: 'Your name',
      yourEmail: 'your@email.com',
      subjectPlaceholder: 'How can we help?',
      messagePlaceholder: 'Tell us more about your inquiry...',
      send: 'Send Message',
      messageSent: 'Message Sent!',
      sentDesc: 'We\'ll get back to you shortly.',
    },
    login: {
      welcome: 'Welcome back to your repair hub.',
      login: 'Login',
      register: 'Register',
      email: 'Email Address',
      password: 'Password',
      forgotPassword: 'Forgot Password?',
      signingIn: 'Signing In...',
      signIn: 'Sign In',
      orContinue: 'or continue with',
      terms: 'By continuing, you agree to our',
      termsOfService: 'Terms of Service',
      and: 'and',
      privacyPolicy: 'Privacy Policy',
      testAccounts: 'Quick login with test accounts',
      admin: 'Admin',
      customer: 'Customer',
    },
  },
  kn: {
    nav: {
      smartphones: 'ಸ್ಮಾರ್ಟ್ಫೋನ್ಗಳು',
      laptops: 'ಲ್ಯಾಪ್ಟಾಪ್ಗಳು',
      accessories: 'ಬಿಡಿಭಾಗಗಳು',
      repairs: 'ದುರಸ್ತಿ',
      about: 'ನಮ್ಮ ಬಗ್ಗೆ',
      contact: 'ಸಂಪರ್ಕ',
      shop: 'ಅಂಗಡಿ',
      signIn: 'ಸೈನ್ ಇನ್',
      dashboard: 'ಡ್ಯಾಶ್ಬೋರ್ಡ್',
      logout: 'ನಿರ್ಗಮಿಸು',
    },
    home: {
      heroBadge: 'ಸ್ಥಾ. 2015',
      heroTitle1: 'ಗುಣಮಟ್ಟದ',
      heroTitle2: 'ನವೀಕರಿಸಿದ',
      heroTitle3: 'ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್',
      heroDesc: 'ಪ್ರತಿ ಸಾಧನವನ್ನು ನಮ್ಮ ತಜ್ಞ ತಂತ್ರಜ್ಞರು ಪರಿಶೀಲಿಸುತ್ತಾರೆ, ಪರೀಕ್ಷಿಸುತ್ತಾರೆ ಮತ್ತು ಪ್ರಮಾಣೀಕರಿಸುತ್ತಾರೆ. 1 ವರ್ಷದ ಖಾತರಿ ಮತ್ತು ಉಚಿತ ಶಿಪ್ಪಿಂಗ್.',
      browseStore: 'ಅಂಗಡಿ ಬ್ರೌಸ್ ಮಾಡಿ',
      bookRepair: 'ದುರಸ್ತಿ ಬುಕ್ ಮಾಡಿ',
      stat1: 'ಪಾಯಿಂಟ್ ತಪಾಸಣೆ',
      stat2: 'ಸಂತೃಪ್ತ ಗ್ರಾಹಕರು',
      stat3: 'ಖಾತರಿ',
      featured: 'ವಿಶೇಷ',
      bestSellers: 'ನಮ್ಮ ಬೆಸ್ಟ್ ಸೆಲ್ಲರ್ಸ್',
      bestSellersDesc: 'ಉನ್ನತ ದರ್ಜೆಯ ಪ್ರಮಾಣೀಕೃತ ಪೂರ್ವ-ಮಾಲೀಕತ್ವದ ಸಾಧನಗಳು.',
      whyChoose: 'ನಮ್ಮನ್ನು ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು',
      whyTitle: 'ಗುಣಮಟ್ಟದ ಮಾನದಂಡವನ್ನು ಹೊಂದಿಸಲಾಗುತ್ತಿದೆ',
      whyTitleAccent: 'ನವೀಕರಿಸಿದ ತಂತ್ರಜ್ಞಾನ',
      whyDesc1: '2015 ರಿಂದ, ಶ್ರೀ ರೇಣುಕಾಂಬ ಕಮ್ಯುನಿಕೇಷನ್ ಪ್ರೀಮಿಯಂ ನವೀಕರಿಸಿದ ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್ ಮತ್ತು ತಜ್ಞ ಮೊಬೈಲ್ ದುರಸ್ತಿ ಸೇವೆಗಳನ್ನು ಒದಗಿಸಲು ಸಮರ್ಪಿತವಾಗಿದೆ.',
      whyDesc2: 'ನಾವು ಮಾರಾಟ ಮಾಡುವ ಪ್ರತಿಯೊಂದು ಸಾಧನವು ನಮ್ಮ ಪ್ರಮಾಣೀಕೃತ ತಂತ್ರಜ್ಞರಿಂದ ಕಟ್ಟುನಿಟ್ಟಾದ 45-ಪಾಯಿಂಟ್ ತಪಾಸಣೆ ಪ್ರಕ್ರಿಯೆಗೆ ಒಳಗಾಗುತ್ತದೆ.',
      val1: '45-ಪಾಯಿಂಟ್ ತಪಾಸಣೆ',
      val2: '30-ದಿನಗಳ ಮರಳಿಸುವಿಕೆ',
      val3: 'ಉಚಿತ ವಿತರಣೆ',
      val4: '1-ವರ್ಷದ ಖಾತರಿ',
      categories: 'ವರ್ಗಗಳು',
      shopByCategory: 'ವರ್ಗದ ಮೂಲಕ ಖರೀದಿಸಿ',
      shopByCategoryDesc: 'ನಮ್ಮ ಆಯ್ಕೆಮಾಡಿದ ಸಾಧನಗಳನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ',
      reviews: 'ವಿಮರ್ಶೆಗಳು',
      whatCustomersSay: 'ನಮ್ಮ ಗ್ರಾಹಕರು ಏನು ಹೇಳುತ್ತಾರೆ',
      stayUpdated: 'ಅಪ್ಡೇಟ್ ಆಗಿರಿ',
      stayUpdatedDesc: 'ಇಮೇಲ್ ಮೂಲಕ ವಿಶೇಷ ಡೀಲ್ಗಳು, ಹೊಸ ಆಗಮನಗಳು ಮತ್ತು ದುರಸ್ತಿ ಸಲಹೆಗಳನ್ನು ಪಡೆಯಿರಿ.',
      subscribe: 'ಸಬ್ಸ್ಕ್ರೈಬ್',
      emailPlaceholder: 'ನಿಮ್ಮ ಇಮೇಲ್ ವಿಳಾಸವನ್ನು ನಮೂದಿಸಿ',
      newStocks: 'ಹೊಸ ಆಗಮನಗಳು',
      newStocksDesc: 'ಇತ್ತೀಚಿನ ಮಾದರಿಗಳು ಮತ್ತು ಅತ್ಯುತ್ತಮ ಡೀಲ್ಗಳೊಂದಿಗೆ ಹೊಸದಾಗಿ ಸೇರಿಸಲಾದ ಸಾಧನಗಳು.',
      justAdded: 'ಈಗ ಸೇರಿಸಲಾಗಿದೆ',
      viewAll: 'ಎಲ್ಲಾ ಉತ್ಪನ್ನಗಳನ್ನು ನೋಡಿ',
    },
    shop: {
      filters: 'ಫಿಲ್ಟರ್ಗಳು',
      search: 'ಹುಡುಕು',
      categories: 'ವರ್ಗಗಳು',
      all: 'ಎಲ್ಲಾ',
      condition: 'ಸ್ಥಿತಿ',
      priceRange: 'ಬೆಲೆ ಶ್ರೇಣಿ',
      clearAll: 'ಎಲ್ಲಾ ಫಿಲ್ಟರ್ಗಳನ್ನು ತೆರವುಗೊಳಿಸಿ',
      sort: 'ವಿಂಗಡಿಸಿ',
      recommended: 'ಶಿಫಾರಸು ಮಾಡಲಾಗಿದೆ',
      addToCart: 'ಸೇರಿಸು',
      outOfStock: 'ಸ್ಟಾಕ್ ಇಲ್ಲ',
      inStock: 'ಸ್ಟಾಕ್ ನಲ್ಲಿ',
      only: 'ಕೇವಲ',
      left: 'ಉಳಿದಿದೆ',
      viewDetails: 'ವಿವರಗಳನ್ನು ನೋಡಿ',
      noProducts: 'ಉತ್ಪನ್ನಗಳು ಕಂಡುಬಂದಿಲ್ಲ',
      noProductsDesc: 'ನಿಮ್ಮ ಫಿಲ್ಟರ್ಗಳನ್ನು ಸರಿಹೊಂದಿಸಿ.',
      available: 'ಲಭ್ಯವಿದೆ',
    },
    product: {
      backTo: 'ಹಿಂತಿರುಗಿ',
      category: 'ವರ್ಗ',
      sku: 'SKU',
      reviews: 'ವಿಮರ್ಶೆಗಳು',
      save: 'ಉಳಿಸಿ',
      description: 'ವಿವರಣೆ',
      specifications: 'ವಿಶೇಷಣಗಳು',
      fullSpecs: 'ಪೂರ್ಣ ವಿಶೇಷಣಗಳು',
      quantity: 'ಪ್ರಮಾಣ',
      addedToCart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಲಾಗಿದೆ',
      addToCart: 'ಕಾರ್ಟ್‌ಗೆ ಸೇರಿಸಿ',
      relatedProducts: 'ಸಂಬಂಧಿತ ಉತ್ಪನ್ನಗಳು',
      certifiedQuality: 'ಪ್ರಮಾಣೀಕೃತ ಗುಣಮಟ್ಟ',
      certifiedDesc: '45-ಪಾಯಿಂಟ್ ತಪಾಸಣೆ',
      freeShipping: 'ಉಚಿತ ಶಿಪ್ಪಿಂಗ್',
      shippingDesc: 'ಎಲ್ಲಾ ಆರ್ಡರ್‌ಗಳಿಗೆ',
      easyReturns: '30-ದಿನಗಳ ಮರಳಿಸುವಿಕೆ',
      returnsDesc: 'ಯಾವುದೇ ಪ್ರಶ್ನೆಗಳಿಲ್ಲ',
      productDetails: 'ಉತ್ಪನ್ನ ವಿವರಗಳು',
    },
    footer: {
      brandDesc: '2015 ರಿಂದ ಪ್ರಮಾಣೀಕೃತ ನವೀಕರಿಸಿದ ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್ ಮತ್ತು ವೃತ್ತಿಪರ ದುರಸ್ತಿ ಸೇವೆಗಳಿಗಾಗಿ ನಿಮ್ಮ ವಿಶ್ವಾಸಾರ್ಹ ಮೂಲ.',
      shop: 'ಅಂಗಡಿ',
      support: 'ಬೆಂಬಲ',
      aboutUs: 'ನಮ್ಮ ಬಗ್ಗೆ',
      bookRepair: 'ದುರಸ್ತಿ ಬುಕ್ ಮಾಡಿ',
      shipping: 'ಶಿಪ್ಪಿಂಗ್ ಮತ್ತು ವಿತರಣೆ',
      returns: 'ಮರಳಿಸುವಿಕೆ ಮತ್ತು ವಿನಿಮಯ',
      faqs: 'FAQ ಗಳು',
      contactUs: 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
      allProducts: 'ಎಲ್ಲಾ ಉತ್ಪನ್ನಗಳು',
      tablets: 'ಟ್ಯಾಬ್ಲೆಟ್‌ಗಳು',
      rights: 'ಎಲ್ಲಾ ಹಕ್ಕುಗಳನ್ನು ಕಾಯ್ದಿರಿಸಲಾಗಿದೆ.',
      privacy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
      terms: 'ಸೇವಾ ನಿಯಮಗಳು',
      cookies: 'ಕುಕೀ ನೀತಿ',
    },
    about: {
      heroTitle: 'ನಮ್ಮ ಬಗ್ಗೆ',
      heroDesc: 'ಶ್ರೀ ರೇಣುಕಾಂಬ ಕಮ್ಯುನಿಕೇಷನ್ 2015 ರಿಂದ ಪ್ರೀಮಿಯಂ ನವೀಕರಿಸಿದ ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್ ಮತ್ತು ವೃತ್ತಿಪರ ದುರಸ್ತಿ ಸೇವೆಗಳಿಗೆ ನಂಬಲರ್ಹ ಹೆಸರಾಗಿದೆ.',
      ourStory: 'ನಮ್ಮ ಕಥೆ',
      storyTitle: 'ಎಲ್ಲರಿಗೂ ಗುಣಮಟ್ಟದ ತಂತ್ರಜ್ಞಾನ',
      storyP1: 'ಬೆಂಗಳೂರಿನಲ್ಲಿ ಸ್ಥಾಪಿತವಾದ ಶ್ರೀ ರೇಣುಕಾಂಬ ಕಮ್ಯುನಿಕೇಷನ್ ಸರಳ ಗುರಿಯೊಂದಿಗೆ ಪ್ರಾರಂಭವಾಯಿತು: ಪ್ರೀಮಿಯಂ ತಂತ್ರಜ್ಞಾನವನ್ನು ಎಲ್ಲರಿಗೂ ಪ್ರವೇಶಿಸುವಂತೆ ಮಾಡುವುದು.',
      storyP2: 'ಪ್ರಮಾಣೀಕೃತ ಪೂರೈಕೆದಾರರೊಂದಿಗೆ ಸಂಬಂಧಗಳನ್ನು ನಿರ್ಮಿಸುವ ಮೂಲಕ ಮತ್ತು ಕಠಿಣ ಪರೀಕ್ಷಾ ಪ್ರೋಟೋಕಾಲ್‌ಗಳನ್ನು ಅಭಿವೃದ್ಧಿಪಡಿಸುವ ಮೂಲಕ, ನಾವು ಆಯ್ಕೆಮಾಡಿದ ಮಾರುಕಟ್ಟೆ ಸ್ಥಳವನ್ನು ರಚಿಸಿದ್ದೇವೆ.',
      storyP3: 'ಇಂದು, ನಾವು ಭಾರತದಾದ್ಯಂತ ಸಾವಿರಾರು ಸಂತೃಪ್ತ ಗ್ರಾಹಕರಿಗೆ ಸೇವೆ ಸಲ್ಲಿಸುತ್ತೇವೆ.',
      happyCustomers: 'ಸಂತೃಪ್ತ ಗ್ರಾಹಕರು',
      devicesSold: 'ಮಾರಾಟವಾದ ಸಾಧನಗಳು',
      avgRating: 'ಸರಾಸರಿ ರೇಟಿಂಗ್',
      yearsExp: 'ವರ್ಷಗಳ ಅನುಭವ',
      whatWeDo: 'ನಾವು ಏನು ಮಾಡುತ್ತೇವೆ',
      whatWeDoDesc: 'ನಮ್ಮನ್ನು ಪ್ರತ್ಯೇಕಿಸುವ ಎರಡು ಪ್ರಮುಖ ಸೇವೆಗಳು',
      ecomTitle: 'ಇ-ಕಾಮರ್ಸ್ ಅಂಗಡಿ',
      ecomDesc: 'ನಾವು ಪ್ರಮಾಣೀಕೃತ ನವೀಕರಿಸಿದ ಎಲೆಕ್ಟ್ರಾನಿಕ್ಸ್ ಅನ್ನು ಆಯ್ಕೆ ಮಾಡಿ ಮಾರಾಟ ಮಾಡುತ್ತೇವೆ - ಸ್ಮಾರ್ಟ್ಫೋನ್‌ಗಳು, ಲ್ಯಾಪ್ಟಾಪ್‌ಗಳು, ಟ್ಯಾಬ್ಲೆಟ್‌ಗಳು ಮತ್ತು ಬಿಡಿಭಾಗಗಳು.',
      repairTitle: 'ದುರಸ್ತಿ ಸೇವೆಗಳು',
      repairDesc: 'ಸ್ಕ್ರೀನ್ ಬದಲಿಯಿಂದ ಬ್ಯಾಟರಿ ಅಪ್‌ಗ್ರೇಡ್ ಮತ್ತು ನೀರಿನ ಹಾನಿ ದುರಸ್ತಿಯವರೆಗೆ, ನಮ್ಮ ಪ್ರಮಾಣೀಕೃತ ತಂತ್ರಜ್ಞರು ಎಲ್ಲಾ ಪ್ರಮುಖ ಬ್ರಾಂಡ್‌ಗಳನ್ನು ನಿಭಾಯಿಸುತ್ತಾರೆ.',
      browseStore: 'ಅಂಗಡಿ ಬ್ರೌಸ್ ಮಾಡಿ',
      bookRepair: 'ದುರಸ್ತಿ ಬುಕ್ ಮಾಡಿ',
      whyChoose: 'ನಮ್ಮನ್ನು ಏಕೆ ಆಯ್ಕೆ ಮಾಡಬೇಕು',
      whyChooseDesc: 'ನಾವು ಪ್ರತಿ ಸಾಧನ ಮತ್ತು ಪ್ರತಿ ದುರಸ್ತಿಯ ಹಿಂದೆ ನಿಲ್ಲುತ್ತೇವೆ',
      meetTeam: 'ನಮ್ಮ ತಂಡವನ್ನು ಭೇಟಿ ಮಾಡಿ',
      meetTeamDesc: 'ಬ್ರಾಂಡ್ ಹಿಂದಿನ ಉತ್ಸಾಹಿ ಜನರು',
      readyToStart: 'ಪ್ರಾರಂಭಿಸಲು ಸಿದ್ಧರಿದ್ದೀರಾ?',
      readyDesc: 'ಪ್ರಮಾಣೀಕೃತ ಸಾಧನಗಳ ನಮ್ಮ ಸಂಗ್ರಹವನ್ನು ಬ್ರೌಸ್ ಮಾಡಿ ಅಥವಾ ಇಂದೇ ದುರಸ್ತಿ ನೇಮಕಾತಿಯನ್ನು ಬುಕ್ ಮಾಡಿ.',
      shopNow: 'ಈಗ ಖರೀದಿಸಿ',
    },
    contact: {
      heroTitle: 'ನಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸಿ',
      heroDesc: 'ಪ್ರಶ್ನೆ ಇದೆಯೇ? ನಿಮ್ಮಿಂದ ಕೇಳಲು ನಾವು ಇಷ್ಟಪಡುತ್ತೇವೆ. ನಮಗೆ ಸಂದೇಶ ಕಳುಹಿಸಿ ಮತ್ತು ನಾವು ಸಾಧ್ಯವಾದಷ್ಟು ಬೇಗ ಪ್ರತಿಕ್ರಿಯಿಸುತ್ತೇವೆ.',
      getInTouch: 'ಸಂಪರ್ಕದಲ್ಲಿರಿ',
      letsTalk: 'ಮಾತನಾಡೋಣ',
      visitUs: 'ಭೇಟಿ ಮಾಡಿ',
      callUs: 'ಕರೆ ಮಾಡಿ',
      emailUs: 'ಇಮೇಲ್ ಮಾಡಿ',
      businessHours: 'ವ್ಯವಹಾರ ಸಮಯ',
      hours: 'ಸೋಮ - ಶನಿ: ಬೆಳಿಗ್ಗೆ 10 - ಸಂಜೆ 8',
      sunHours: 'ಭಾನುವಾರ: ಬೆಳಿಗ್ಗೆ 11 - ಸಂಜೆ 5',
      quickResponse: 'ತ್ವರಿತ ಪ್ರತಿಕ್ರಿಯೆ',
      quickDesc: 'ನಾವು ಸಾಮಾನ್ಯವಾಗಿ ವ್ಯವಹಾರ ಸಮಯದಲ್ಲಿ 2-4 ಗಂಟೆಗಳ ಒಳಗೆ ಪ್ರತಿಕ್ರಿಯಿಸುತ್ತೇವೆ. ತುರ್ತು ದುರಸ್ತಿಗಾಗಿ, ದಯವಿಟ್ಟು ನಮಗೆ ನೇರವಾಗಿ ಕರೆ ಮಾಡಿ.',
      sendMessage: 'ಸಂದೇಶ ಕಳುಹಿಸಿ',
      fullName: 'ಪೂರ್ಣ ಹೆಸರು',
      email: 'ಇಮೇಲ್',
      subject: 'ವಿಷಯ',
      message: 'ಸಂದೇಶ',
      yourName: 'ನಿಮ್ಮ ಹೆಸರು',
      yourEmail: 'ನಿಮ್ಮ@ಇಮೇಲ್.ಕಾಂ',
      subjectPlaceholder: 'ನಾವು ಹೇಗೆ ಸಹಾಯ ಮಾಡಬಹುದು?',
      messagePlaceholder: 'ನಿಮ್ಮ ವಿಚಾರಣೆಯ ಬಗ್ಗೆ ಇನ್ನಷ್ಟು ತಿಳಿಸಿ...',
      send: 'ಸಂದೇಶ ಕಳುಹಿಸಿ',
      messageSent: 'ಸಂದೇಶ ಕಳುಹಿಸಲಾಗಿದೆ!',
      sentDesc: 'ನಾವು ಶೀಘ್ರದಲ್ಲೇ ನಿಮ್ಮನ್ನು ಸಂಪರ್ಕಿಸುತ್ತೇವೆ.',
    },
    login: {
      welcome: 'ನಿಮ್ಮ ದುರಸ್ತಿ ಕೇಂದ್ರಕ್ಕೆ ಮರಳಿ ಸ್ವಾಗತ.',
      login: 'ಲಾಗಿನ್',
      register: 'ನೋಂದಣಿ',
      email: 'ಇಮೇಲ್ ವಿಳಾಸ',
      password: 'ಪಾಸ್ವರ್ಡ್',
      forgotPassword: 'ಪಾಸ್ವರ್ಡ್ ಮರೆತಿರಾ?',
      signingIn: 'ಸೈನ್ ಇನ್ ಆಗುತ್ತಿದೆ...',
      signIn: 'ಸೈನ್ ಇನ್',
      orContinue: 'ಅಥವಾ ಮುಂದುವರಿಸಿ',
      terms: 'ಮುಂದುವರಿಸುವ ಮೂಲಕ, ನೀವು ನಮ್ಮ',
      termsOfService: 'ಸೇವಾ ನಿಯಮಗಳು',
      and: 'ಮತ್ತು',
      privacyPolicy: 'ಗೌಪ್ಯತಾ ನೀತಿ',
      testAccounts: 'ಪರೀಕ್ಷಾ ಖಾತೆಗಳೊಂದಿಗೆ ತ್ವರಿತ ಲಾಗಿನ್',
      admin: 'ನಿರ್ವಾಹಕ',
      customer: 'ಗ್ರಾಹಕ',
    },
  },
};

const LanguageContext = createContext();

export function LanguageProvider({ children }) {
  const [lang, setLang] = useState(() => localStorage.getItem('lang') || 'en');

  const switchLang = (l) => {
    setLang(l);
    localStorage.setItem('lang', l);
  };

  const t = (path) => {
    const keys = path.split('.');
    let val = translations[lang];
    for (const k of keys) {
      if (val) val = val[k];
    }
    return val || path;
  };

  return (
    <LanguageContext.Provider value={{ lang, switchLang, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export const useLanguage = () => useContext(LanguageContext);
